#!/bin/bash -ex
cd buildroot
scp Marlin/Marlin.MightyCore.avr.1284.hex pi@octopi:.
ssh pi@octopi "avrdude -C /etc/avrdude.conf -v -p atmega1284p -carduino -P ${1:-/dev/ttyUSB0} -b115200 -D -Uflash:w:Marlin.MightyCore.avr.1284.hex:i"
